codebase/kimai/src/Entity/Activity.php
<?php

/*
 * This file is part of the Kimai time-tracking app.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Entity;

use App\Doctrine\Behavior\CreatedAt;
use App\Doctrine\Behavior\CreatedTrait;
use App\Export\Annotation as Exporter;
use App\Repository\ActivityRepository;
use App\Validator\Constraints as Constraints;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation as Serializer;
use OpenApi\Attributes as OA;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Table(name: 'kimai2_activities')]
#[ORM\Index(columns: ['visible', 'project_id'])]
#[ORM\Index(columns: ['visible', 'project_id', 'name'])]
#[ORM\Index(columns: ['visible', 'name'])]
#[ORM\Entity(repositoryClass: ActivityRepository::class)]
#[ORM\ChangeTrackingPolicy('DEFERRED_EXPLICIT')]
#[Serializer\ExclusionPolicy('all')]
#[Serializer\VirtualProperty('ProjectName', exp: 'object.getProject() === null ? null : object.getProject().getName()', options: [new Serializer\SerializedName('parentTitle'), new Serializer\Type(name: 'string'), new Serializer\Groups(['Activity'])])]
#[Serializer\VirtualProperty('ProjectAsId', exp: 'object.getProject() === null ? null : object.getProject().getId()', options: [new Serializer\SerializedName('project'), new Serializer\Type(name: 'integer'), new Serializer\Groups(['Activity', 'Team', 'Not_Expanded'])])]
#[Exporter\Order(['id', 'name', 'project', 'budget', 'timeBudget', 'budgetType', 'color', 'visible', 'comment', 'billable', 'number'])]
#[Exporter\Expose(name: 'project', label: 'project', exp: 'object.getProject() === null ? null : object.getProject().getName()')]
#[Constraints\Activity]
class Activity implements EntityWithMetaFields, EntityWithBudget, CreatedAt
{
    use BudgetTrait;
    use ColorTrait;
    use CreatedTrait;

    /**
     * Unique activity ID
     */
    #[ORM\Column(name: 'id', type: Types::INTEGER)]
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'IDENTITY')]
    #[Serializer\Expose]
    #[Serializer\Groups(['Default'])]
    #[Exporter\Expose(label: 'id', type: 'integer')]
    private ?int $id = null;
    #[ORM\ManyToOne(targetEntity: Project::class)]
    #[ORM\JoinColumn(nullable: true, onDelete: 'CASCADE')]
    #[Serializer\Expose]
    #[Serializer\Groups(['Expanded'])]
    #[OA\Property(ref: '#/components/schemas/ProjectExpanded')]
    private ?Project $project = null;
    /**
     * Name of this activity
     */
    #[ORM\Column(name: 'name', type: Types::STRING, length: 150, nullable: false)]
    #[Assert\NotBlank]
    #[Assert\Length(min: 2, max: 150)]
    #[Serializer\Expose]
    #[Serializer\Groups(['Default'])]
    #[Exporter\Expose(label: 'name')]
    private ?string $name = null;
    /**
     * Description of this activity
     */
    #[ORM\Column(name: 'comment', type: Types::TEXT, nullable: true)]
    #[Serializer\Expose]
    #[Serializer\Groups(['Default'])]
    #[Exporter\Expose(label: 'comment')]
    private ?string $comment = null;
    /**
     * Whether this activity is visible and can be selected
     */
    #[ORM\Column(name: 'visible', type: Types::BOOLEAN, nullable: false, options: ['default' => true])]
    #[Assert\NotNull]
    #[Serializer\Expose]
    #[Serializer\Groups(['Default'])]
    #[Exporter\Expose(label: 'visible', type: 'boolean')]
    private bool $visible = true;
    #[ORM\Column(name: 'billable', type: Types::BOOLEAN, nullable: false, options: ['default' => true])]
    #[Assert\NotNull]
    #[Serializer\Expose]
    #[Serializer\Groups(['Default'])]
    #[Exporter\Expose(label: 'billable', type: 'boolean')]
    private bool $billable = true;
    /**
     * Meta fields registered with the activity
     *
     * @var Collection<ActivityMeta>
     */
    #[ORM\OneToMany(mappedBy: 'activity', targetEntity: ActivityMeta::class, cascade: ['persist'])]
    #[Serializer\Expose]
    #[Serializer\Groups(['Default'])]
    #[Serializer\Type(name: 'array<App\Entity\ActivityMeta>')]
    #[Serializer\SerializedName('metaFields')]
    #[Serializer\Accessor(getter: 'getVisibleMetaFields')]
    private Collection $meta;
    /**
     * Teams with access to the activity
     *
     * @var Collection<Team>
     */
    #[ORM\JoinTable(name: 'kimai2_activities_teams')]
    #[ORM\JoinColumn(name: 'activity_id', referencedColumnName: 'id', onDelete: 'CASCADE')]
    #[ORM\InverseJoinColumn(name: 'team_id', referencedColumnName: 'id', onDelete: 'CASCADE')]
    #[ORM\ManyToMany(targetEntity: Team::class, inversedBy: 'activities', cascade: ['persist'])]
    #[Serializer\Expose]
    #[Serializer\Groups(['Activity'])]
    #[OA\Property(type: 'array', items: new OA\Items(ref: '#/components/schemas/Team'))]
    private Collection $teams;
    #[ORM\Column(name: 'invoice_text', type: Types::TEXT, nullable: true)]
    private ?string $invoiceText = null;
    #[ORM\Column(name: 'number', type: Types::STRING, length: 10, nullable: true)]
    #[Assert\Length(max: 10)]
    #[Serializer\Expose]
    #[Serializer\Groups(['Default'])]
    #[Exporter\Expose(label: 'activity_number')]
    private ?string $number = null;

    public function __construct()
    {
        $this->meta = new ArrayCollection();
        $this->teams = new ArrayCollection();
        $this->setCreatedAt(new \DateTimeImmutable('now', new \DateTimeZone('UTC')));
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function isNew(): bool
    {
        return $this->id === null;
    }

    public function getProject(): ?Project
    {
        return $this->project;
    }

    public function setProject(?Project $project): Activity
    {
        $this->project = $project;

        return $this;
    }

    public function setName(string $name): Activity
    {
        $this->name = $name;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setComment(?string $comment): Activity
    {
        $this->comment = $comment;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setVisible(bool $visible): Activity
    {
        $this->visible = $visible;

        return $this;
    }

    public function isGlobal(): bool
    {
        return $this->project === null;
    }

    public function isVisible(): bool
    {
        return $this->visible;
    }

    public function setBillable(bool $billable): void
    {
        $this->billable = $billable;
    }

    public function isBillable(): bool
    {
        return $this->billable;
    }

    /**
     * @return Collection|MetaTableTypeInterface[]
     */
    public function getMetaFields(): Collection
    {
        return $this->meta;
    }

    /**
     * @return MetaTableTypeInterface[]
     */
    public function getVisibleMetaFields(): array
    {
        $all = [];
        foreach ($this->meta as $meta) {
            if ($meta->isVisible()) {
                $all[] = $meta;
            }
        }

        return $all;
    }

    public function getMetaField(string $name): ?MetaTableTypeInterface
    {
        foreach ($this->meta as $field) {
            if (strtolower($field->getName()) === strtolower($name)) {
                return $field;
            }
        }

        return null;
    }

    public function setMetaField(MetaTableTypeInterface $meta): EntityWithMetaFields
    {
        if (null === ($current = $this->getMetaField($meta->getName()))) {
            $meta->setEntity($this);
            $this->meta->add($meta);

            return $this;
        }

        $current->merge($meta);

        return $this;
    }

    public function addTeam(Team $team): void
    {
        if ($this->teams->contains($team)) {
            return;
        }

        $this->teams->add($team);
        $team->addActivity($this);
    }

    public function removeTeam(Team $team): void
    {
        if (!$this->teams->contains($team)) {
            return;
        }
        $this->teams->removeElement($team);
        $team->removeActivity($this);
    }

    /**
     * @return Collection<Team>
     */
    public function getTeams(): Collection
    {
        return $this->teams;
    }

    public function getInvoiceText(): ?string
    {
        return $this->invoiceText;
    }

    public function setInvoiceText(?string $invoiceText): void
    {
        $this->invoiceText = $invoiceText;
    }

    public function setNumber(?string $number): void
    {
        $this->number = $number;
    }

    public function getNumber(): ?string
    {
        return $this->number;
    }

    public function __toString(): string
    {
        return $this->getName();
    }

    public function __clone()
    {
        if ($this->id !== null) {
            $this->id = null;
        }

        $this->setCreatedAt(new \DateTimeImmutable('now', new \DateTimeZone('UTC')));

        $currentTeams = $this->teams;
        $this->teams = new ArrayCollection();
        /** @var Team $team */
        foreach ($currentTeams as $team) {
            $this->addTeam($team);
        }

        $this->number = null;
        $currentMeta = $this->meta;
        $this->meta = new ArrayCollection();
        /** @var ActivityMeta $meta */
        foreach ($currentMeta as $meta) {
            $newMeta = clone $meta;
            $newMeta->setEntity($this);
            $this->setMetaField($newMeta);
        }
    }
}

codebase/kimai/src/Entity/Role.php
<?php

/*
 * This file is part of the Kimai time-tracking app.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Entity;

use App\Repository\RoleRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Table(name: 'kimai2_roles')]
#[ORM\UniqueConstraint(name: 'roles_name', columns: ['name'])]
#[ORM\Entity(repositoryClass: RoleRepository::class)]
#[ORM\ChangeTrackingPolicy('DEFERRED_EXPLICIT')]
#[UniqueEntity('name')]
class Role
{
    #[ORM\Column(name: 'id', type: Types::INTEGER)]
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'IDENTITY')]
    private ?int $id = null;
    #[ORM\Column(name: 'name', type: Types::STRING, length: 50, nullable: false)]
    #[Assert\NotNull]
    #[Assert\NotBlank]
    #[Assert\Length(min: 5, max: 50)]
    private ?string $name = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): Role
    {
        $this->name = strtoupper($name);

        return $this;
    }

    public function isUser(): bool
    {
        return $this->name === User::ROLE_USER;
    }
}

codebase/kimai/src/Form/Helper/ProjectHelper.php
<?php

/*
 * This file is part of the Kimai time-tracking app.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Form\Helper;

use App\Configuration\LocaleService;
use App\Configuration\SystemConfiguration;
use App\Entity\Project;
use Symfony\Contracts\Translation\TranslatorInterface;

final class ProjectHelper
{
    public const PATTERN_NAME = '{name}';
    public const PATTERN_NUMBER = '{number}';
    public const PATTERN_COMMENT = '{comment}';
    public const PATTERN_ORDERNUMBER = '{orderNumber}';
    public const PATTERN_DATERANGE = '{daterange}';
    public const PATTERN_START = '{start}';
    public const PATTERN_END = '{end}';
    public const PATTERN_CUSTOMER = '{parentTitle}';
    public const PATTERN_SPACER = '{spacer}';
    public const SPACER = ' - ';

    private ?\IntlDateFormatter $dateFormatter = null;
    private ?string $pattern = null;
    private bool $showStart = false;
    private bool $showEnd = false;
    private ?string $locale = null;

    public function __construct(
        private readonly SystemConfiguration $configuration,
        private readonly LocaleService $localeService,
        private readonly TranslatorInterface $translator
    )
    {
    }

    public function getLocale(): string
    {
        return $this->locale ?? \Locale::getDefault();
    }

    public function setLocale(?string $locale): void
    {
        $this->locale = $locale;
    }

    public function getChoicePattern(): string
    {
        if ($this->pattern === null) {
            $this->pattern = $this->configuration->find('project.choice_pattern');

            if ($this->pattern === null || stripos($this->pattern, '{') === false || stripos($this->pattern, '}') === false) {
                $this->pattern = self::PATTERN_NAME;
            }

            $this->pattern = str_replace(self::PATTERN_DATERANGE, self::PATTERN_START . '-' . self::PATTERN_END, $this->pattern);
            $this->pattern = str_replace(self::PATTERN_SPACER, self::SPACER, $this->pattern);
        }

        return $this->pattern;
    }

    public function getChoiceLabel(Project $project): string
    {
        $name = $this->getChoicePattern();
        $name = str_replace(self::PATTERN_NAME, $project->getName() ?? '', $name);
        $name = str_replace(self::PATTERN_NUMBER, $project->getNumber() ?? '', $name);
        $name = str_replace(self::PATTERN_COMMENT, $project->getComment() ?? '', $name);
        $name = str_replace(self::PATTERN_CUSTOMER, $project->getCustomer()?->getName() ?? '', $name);
        $name = str_replace('{ordernumber}', self::PATTERN_ORDERNUMBER, $name); // this was a typo before Kimai 2.38, can be removed in the future
        $name = str_replace(self::PATTERN_ORDERNUMBER, $project->getOrderNumber() ?? '', $name);

        if ($this->dateFormatter === null) {
            $this->showStart = stripos($name, self::PATTERN_START) !== false;
            $this->showEnd = stripos($name, self::PATTERN_END) !== false;
            $locale = $this->getLocale();
            $this->dateFormatter = new \IntlDateFormatter(
                $locale,
                \IntlDateFormatter::MEDIUM,
                \IntlDateFormatter::MEDIUM,
                date_default_timezone_get(),
                \IntlDateFormatter::GREGORIAN,
                $this->localeService->getDateFormat($locale)
            );
        }

        if ($this->showStart) {
            $start = '';
            if ($project->getStart() !== null) {
                $start = $this->translator->trans('project_start') . ': ' . $this->dateFormatter->format($project->getStart());
            }
            $name = str_replace(self::PATTERN_START, $start, $name);
        }

        if ($this->showEnd) {
            $end = '';
            if ($project->getEnd() !== null) {
                $end = $this->translator->trans('project_end') . ': ' . $this->dateFormatter->format($project->getEnd());
            }
            $name = str_replace(self::PATTERN_END, $end, $name);
        }

        while (str_starts_with($name, self::SPACER)) {
            $name = substr($name, \strlen(self::SPACER));
        }

        while (str_ends_with($name, self::SPACER)) {
            $name = substr($name, 0, -\strlen(self::SPACER));
        }

        if ($name === '' || $name === self::SPACER) {
            $name = $project->getName() ?? '';
        }

        return substr($name, 0, 110);
    }
}

codebase/kimai/templates/project/actions.html.twig
{% macro project(project, view, isTable, params) %}
    {% import "macros/widgets.html.twig" as widgets %}
    {% set event = actions(app.user, 'project', view, params|default({})|merge({'project': project, 'token': csrf_token('project.duplicate')})) %}
    {% if view == 'index' or view == 'custom' or isTable is not null %}
        {{ widgets.table_actions(event.actions) }}
    {% else %}
        {{ widgets.page_actions(event.actions) }}
    {% endif %}
{% endmacro %}

codebase/kimai/templates/project/charts.html.twig
{# project \App\Entity\Project #}
{# details \App\Reporting\ProjectDetails\ProjectDetailsModel #}
{% macro project_budget(project, details, prefix) %}
    {% set chartPrefix = (prefix is null ? random() : prefix) ~ 'Budget' %}
    {% set chart = is_granted('budget', project) %}
    {% set showMoneyBudget = is_granted('budget', project) and project.hasBudget() %}
    {% set showTimeBudget = is_granted('time', project) and project.hasTimeBudget() %}
    {% if showMoneyBudget or showTimeBudget %}
        {% from "macros/charts.html.twig" import bar_chart %}
        {% set currency = project.customer.currency %}
        {% if project.isMonthlyBudget() %}
            <h4>
                {%- if showMoneyBudget %}{{ 'budget'|trans }}{% else %}{{ 'timeBudget'|trans }}{% endif -%}
                : {{ 'budgetType_month'|trans }}
            </h4>
            {% set chartData = [] %}
            {% set chartLabels = [] %}
            {# year \App\Model\Statistic\Year #}
            {% for year in details.years %}
                {# month \App\Model\Statistic\Month #}
                {% for month in year.months %}
                    {% set monthDate = date(year.year ~ '-' ~ month.month ~ '-01 00:00:00') %}
                    {% if project.end is null or monthDate < project.end %}
                        {% set totalBudget = project.getTimeBudget() - month.billableDuration %}
                        {% set projectBudget = project.getTimeBudget() %}
                        {% if showMoneyBudget %}
                            {% set totalBudget = project.getBudget() - month.billableRate %}
                            {% set projectBudget = project.getBudget() %}
                        {% endif %}
                        {% set chartLabels = chartLabels|merge([monthDate|month_name ~ ' ' ~ year.year]) %}
                        {% set chartValue = {
                            'label': (showMoneyBudget ? totalBudget|money(currency) : totalBudget|duration),
                            'value': '' ~ (showMoneyBudget ? totalBudget|chart_money : totalBudget|chart_duration),
                        } %}
                        {% if totalBudget < 0 %}
                            {% set chartValue = chartValue|merge({'color': 'red'}) %}
                        {% endif %}
                        {% if totalBudget == projectBudget %}
                            {% set chartValue = chartValue|merge({'color': 'green'}) %}
                        {% endif %}
                        {% set chartData = chartData|merge([chartValue]) %}
                    {% endif %}
                {% endfor %}
            {% endfor %}
            {{ bar_chart(chartPrefix, chartLabels, [chartData], {'height': '300px', 'renderEvent': 'render.' ~ chartPrefix}) }}
        {% else %}
            <h4>
                {%- if showMoneyBudget %}{{ 'budget'|trans }}{% else %}{{ 'timeBudget'|trans }}{% endif -%}
            </h4>
            {% set chartData = [] %}
            {% set chartLabels = [] %}
            {% if showMoneyBudget %}
                {% set totalBudget = project.getBudget() %}
            {% else %}
                {% set totalBudget = project.getTimeBudget() %}
            {% endif %}
            {# year \App\Model\Statistic\Year #}
            {% for year in details.years %}
                {# month \App\Model\Statistic\Month #}
                {% for month in year.months %}
                    {% set monthDate = date(year.year ~ '-' ~ month.month ~ '-01') %}
                    {% if project.end is null or monthDate < project.end %}
                        {% if showMoneyBudget %}
                            {% set totalBudget = totalBudget - month.billableRate %}
                        {% else %}
                            {% set totalBudget = totalBudget - month.billableDuration %}
                        {% endif %}
                        {% set chartLabels = chartLabels|merge([monthDate|month_name ~ ' ' ~ year.year]) %}
                        {% set chartValue = {
                            'label': (showMoneyBudget ? totalBudget|money(currency) : totalBudget|duration),
                            'value': (showMoneyBudget ? totalBudget|chart_money : totalBudget|chart_duration),
                        } %}
                        {% if totalBudget < 0 %}
                            {% set chartValue = chartValue|merge({'color': 'red'}) %}
                        {% endif %}
                        {% set chartData = chartData|merge([chartValue]) %}
                    {% endif %}
                {% endfor %}
            {% endfor %}
            {% set last = chartData|last %}
            {% if last is not empty and last.value > 0 %}
                {% set chartValueZero = {
                    'label': (showMoneyBudget ? 0|money(currency) : 0|duration),
                    'value': (showMoneyBudget ? 0|chart_money : 0|chart_duration),
                } %}
                {% set chartData = chartData|merge([chartValueZero]) %}
            {% endif %}
            {{ bar_chart(chartPrefix, chartLabels, [chartData], {'height': '300px', 'renderEvent': 'render.' ~ chartPrefix, 'type': 'line'}) }}
        {% endif %}
    {% endif %}
{% endmacro %}

codebase/kimai/templates/project/delete.html.twig
{% extends kimai_context.modalRequest ? 'form.html.twig' : 'base.html.twig' %}

{% block main %}
    {% set params = {
        '%records%': stats.counter,
        '%duration%': stats.duration|duration
    } %}
    {{ include(kimai_context.modalRequest ? 'default/_form_delete_modal.html.twig' : 'default/_form_delete.html.twig', {
        'message': ("delete_warning.short_stats"|trans(params) ~ "admin_entity.delete_confirm"|trans),
        'form': form,
        'delete_item_name': project.name,
        'used': (stats.counter > 0),
        'back': path('admin_project')
    }) }}
{% endblock %}

codebase/kimai/templates/project/details.html.twig
{% extends 'base.html.twig' %}
{% import "macros/widgets.html.twig" as widgets %}

{% block main %}
    {% set can_edit = is_granted('edit', project) %}

    {% embed '@theme/embeds/card.html.twig' %}
        {% import "macros/widgets.html.twig" as widgets %}
        {% import "customer/actions.html.twig" as customerActions %}
        {% block box_attributes %}id="project_details_box"{% endblock %}
        {% block box_tools %}
            {% if can_edit %}
                {{ widgets.card_tool_button('edit', {'class': 'modal-ajax-form open-edit', 'title': 'edit', 'url': path('admin_project_edit', {'id': project.id})}) }}
            {% endif %}
        {% endblock %}
        {% block box_title %}
            {{ widgets.label_dot(project.name, project.color) }}
        {% endblock %}
        {% block box_body_class %}p-0{% endblock %}
        {% block box_body %}
            {% if project.comment is not empty %}
                <div class="comment p-3">
                    {{ project.comment|comment2html(true) }}
                </div>
            {% endif %}
            <table class="table table-hover dataTable">
                {% if not project.visible %}
                    <tr class="{{ widgets.class_project_row(project, now) }}">
                        <th>{{ 'visible'|trans }}</th>
                        <td colspan="3">
                            {{ widgets.label_boolean(project.visible) }}
                        </td>
                    </tr>
                {% endif %}
                <tr {{ widgets.customer_row_attr(project.customer, now) }}>
                    <th>{{ 'customer'|trans }}</th>
                    <td>
                        {{ widgets.label_customer(project.customer) }}
                    </td>
                    <td class="w-min">
                        {{ widgets.badge_team_access(project.customer.teams) }}
                    </td>
                    <td class="actions">
                        {{ customerActions.customer(project.customer, 'custom') }}
                    </td>
                </tr>
                {% if is_granted('details', project) %}
                    {% if not project.billable %}
                        <tr>
                            <th>{{ 'billable'|trans }}</th>
                            <td colspan="3">
                                {{ widgets.label_boolean(project.billable) }}
                            </td>
                        </tr>
                    {% endif %}
                    {% if project.orderNumber is not empty %}
                    <tr>
                        <th>{{ 'orderNumber'|trans }}</th>
                        <td colspan="3">
                            {{ project.orderNumber }}
                        </td>
                    </tr>
                    {% endif %}
                    {% if project.orderDate is not empty %}
                    <tr>
                        <th>{{ 'orderDate'|trans }}</th>
                        <td colspan="3">
                            {{ project.orderDate|date_short }}
                        </td>
                    </tr>
                    {% endif %}
                    {% if project.start is not empty %}
                    <tr>
                        <th>{{ 'project_start'|trans }}</th>
                        <td colspan="3">
                            {{ project.start|date_short }}
                        </td>
                    </tr>
                    {% endif %}
                    {% if project.end is not empty %}
                    <tr>
                        <th>{{ 'project_end'|trans }}</th>
                        <td colspan="3">
                            {{ project.end|date_short }}
                        </td>
                    </tr>
                    {% endif %}
                    {% if project.number is not empty %}
                    <tr>
                        <th>{{ 'project_number'|trans }}</th>
                        <td colspan="3">
                            {{ project.number }}
                        </td>
                    </tr>
                    {% endif %}
                {% endif %}
                {% if project.hasBudget() and is_granted('budget', project) %}
                    <tr>
                        <th>
                            {{ 'budget'|trans }}
                            {% if project.isMonthlyBudget() %}
                                ({{ 'budgetType_month'|trans }})
                            {% endif %}
                        </th>
                        <td colspan="3">
                            {{ project.getBudget()|money(project.customer.currency) }}
                        </td>
                    </tr>
                {% endif %}
                {% if project.hasTimeBudget() and is_granted('time', project) %}
                    <tr>
                        <th>
                            {{ 'timeBudget'|trans }}
                            {% if project.isMonthlyBudget() %}
                                ({{ 'budgetType_month'|trans }})
                            {% endif %}
                        </th>
                        <td colspan="3">
                            {{ project.getTimeBudget()|duration }}
                        </td>
                    </tr>
                {% endif %}
                {% if not project.globalActivities %}
                    <tr>
                        <th>{{ 'globalActivities'|trans }}</th>
                        <td colspan="3">
                            {{ widgets.label_boolean(project.globalActivities) }}
                        </td>
                    </tr>
                {% endif %}
                {% for metaField in project.visibleMetaFields|filter(field => field.defined)|sort((a, b) => a.order <=> b.order) %}
                    <tr>
                        <th>{{ metaField.label|trans }}</th>
                        <td colspan="3">{{ widgets.form_type_value(metaField.type, metaField.value, project) }}</td>
                    </tr>
                {% endfor %}
            </table>
        {% endblock %}
    {% endembed %}

    {{ render(controller('App\\Controller\\ProjectController::activitiesAction', {'project': project.id, 'page': 1})) }}

    {% if can_edit %}
        {{ include('embeds/rates-table.html.twig', {'id': 'project_rates_box', 'entity': project, 'create_url': path('admin_project_rate_add', {'id': project.id}), 'delete_route': 'delete_project_rate', 'currency': project.customer.currency, 'edit_route': 'admin_project_rate_edit'}) }}
    {% endif %}

    {% if stats is not null %}
        {{ include('embeds/budgets.html.twig', {'entity': project, 'stats': stats, 'currency': project.customer.currency}) }}
    {% endif %}

    {% for controller in boxes %}
        {{ render(controller(controller, {'project': project, 'page': 1})) }}
    {% endfor %}

    {% if teams is not null%}
        {% set options = {'teams': teams, 'team': team} %}
        {% if is_granted('permissions', project) %}
            {% set options = options|merge({'route_create': path('project_team_create', {'id': project.id}), 'route_edit': path('admin_project_permissions', {'id': project.id})}) %}
        {% endif %}
        {% if project.customer.teams|length > 0 %}
            {% set options = options|merge({'empty_message': 'team.project_visibility_inherited'}) %}
        {% endif %}
        {{ include('embeds/teams.html.twig', options) }}
    {% endif %}

    {% if comments is not null %}
        {% set options = {'form': commentForm, 'comments': comments} %}
        {% if can_edit %}
            {% set options = options|merge({'route_pin': 'project_comment_pin', 'route_delete': 'project_comment_delete'}) %}
        {% endif %}
        {{ include('embeds/comments.html.twig', options) }}
    {% endif %}

{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script type="text/javascript">
        document.addEventListener('kimai.initialized', function() {
            KimaiReloadPageWidget.create('kimai.customerTeamUpdate kimai.projectTeamUpdate kimai.activityTeamUpdate kimai.projectUpdate kimai.teamUpdate kimai.customerUpdate kimai.rateUpdate');
        });
    </script>
{% endblock %}

codebase/kimai/templates/project/permissions.html.twig
{% extends kimai_context.modalRequest ? 'form.html.twig' : 'base.html.twig' %}

{% block main %}
    {{ include(kimai_context.modalRequest ? 'default/_form_modal.html.twig' : 'default/_form.html.twig', {
        'title': ('permissions'|trans) ~ ': ' ~ project.name,
        'form': form,
        'back': path('project_details', {'id': project.id})
    }) }}
{% endblock %}

codebase/kimai/templates/project/rates.html.twig
{% extends kimai_context.modalRequest ? 'form.html.twig' : 'base.html.twig' %}

{% block main %}
    {{ include(kimai_context.modalRequest ? 'default/_form_modal.html.twig' : 'default/_form.html.twig', {
        'title': project.name,
        'form': form,
        'back': path('admin_project')
    }) }}
{% endblock %}